extern void __VERIFIER_error() __attribute__ ((__noreturn__));
extern void immediate_notify(void);
extern int __VERIFIER_nondet_int();
/* Generated by CIL v. 1.3.6 */
/* print_CIL_Input is true */

void error(void)
{
  
  {
  ERROR: __VERIFIER_error();
    return;
  }
}

int main(void) 
{
  int m_pc  =    0;
  int m_st  ;
  int E_1  =    2;
  
  {
    if (m_pc == 0) {
      goto M_ENTRY;
    } else {
      if (m_pc == 1) {
        goto M_WAIT;
      } else {
        
      }
    }
  M_ENTRY: ;
    {
      while (1) {
      while_0_continue: /* CIL Label */ ;
        {
          E_1 = 1;
          immediate_notify();
          E_1 = 2;
        }
        {
          while (1) {
          while_1_continue: /* CIL Label */ ;
            m_pc = 1;
            m_st = 2;
            
            goto return_label;
          M_WAIT: ;
          }
        while_1_break: /* CIL Label */ ;
        }
      }
    while_0_break: /* CIL Label */ ;
    }
    
  return_label: /* CIL Label */
    return 0;
  }
}